---
- hosts: all
  become: true
  tasks:
    - name: update repository index and install apache2 and php package
      apt:
        update_cache: yes
        name:
          - apache2
          - libapache2-mod-php
        state: latest
    - name: set up default webpage
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
